name: Workflow con Python

on:
  push:
    branches:
      - oscar
  workflow_dispatch:

jobs:
  ejecutar-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Ejecutar script Python
        run: python 07_scraping/01_basic.py
